// <auto-generated />
using API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DBInteractor))]
    [Migration("20200507175331_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Domain.Model.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Woerden",
                            Country = "Netherlands",
                            HouseNumber = 11,
                            PostalCode = "3446XP",
                            Street = "Forintdreef"
                        },
                        new
                        {
                            Id = 2L,
                            City = "Woerden",
                            Country = "Netherlands",
                            HouseNumber = 5,
                            PostalCode = "3441AP",
                            Street = "Eendrachtstraat"
                        },
                        new
                        {
                            Id = 3L,
                            City = "Woerden",
                            Country = "Netherlands",
                            HouseNumber = 86,
                            PostalCode = "3446JG",
                            Street = "Kallameer"
                        },
                        new
                        {
                            Id = 4L,
                            City = "Woerden",
                            Country = "Netherlands",
                            HouseNumber = 2,
                            PostalCode = "3446JL",
                            Street = "Tornemeer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
